services:
  - docker

before_install:
- echo $APP_ENV
- docker build -t react-travis-dev -f Dockerfile.dev .

script:
- docker run -e CI=true react-travis-dev npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  region: "us-east-1"
  app: "docker-lco"
  env: "DockerLco-env"
  bucket_name: "elasticbeanstalk-us-east-1-166606814517"
  bucket_path: "docker-lco"