services:
  - docker

before_install:
- docker build -t react-travis-dev -f Dockerfile .

script:
- docker run -e CI=true react-travis-dev npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  region: "us-east-1"
  app: "react-travis-docker"
  env: "ReactTravisDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-166606814517"